import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";  // Adjust the path based on your structure
import Footer from "../components/Footer"; 

const poppins = Poppins({
  variable: "--font-poppins",  // Custom variable name
  subsets: ["latin"],          // You can add more subsets if needed
  weight: ["400", "500", "700"], // Array of multiple weights
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased`}
      >
        <Header />
        {children}
        <Footer /> 
      </body>
    </html>
  );
}
